import PropTypes from "prop-types";

import Select from "react-select";
import makeAnimated from "react-select/animated";
const animatedComponents = makeAnimated();

const options = [
  { value: "politics", label: "Politics" },
  { value: "election", label: "Election" },
  { value: "government", label: "Government" },
  { value: "policy", label: "Policy" },
  { value: "congress", label: "Congress" },
  { value: "senate", label: "Senate" },
  { value: "campaign", label: "Campaign" },
  { value: "diplomacy", label: "Diplomacy" },
  { value: "legislation", label: "Legislation" },
  { value: "political_debate", label: "Political Debate" },
  { value: "international_relations", label: "International Relations" },
  { value: "law", label: "Law" },
  { value: "business", label: "Business" },
  { value: "finance", label: "Finance" },
  { value: "economy", label: "Economy" },
  { value: "market", label: "Market" },
  { value: "entrepreneurship", label: "Entrepreneurship" },
  { value: "investment", label: "Investment" },
  { value: "corporate", label: "Corporate" },
  { value: "startup", label: "Startup" },
  { value: "stock_market", label: "Stock Market" },
  { value: "technology", label: "Technology" },
  { value: "innovation", label: "Innovation" },
  { value: "AI", label: "AI" },
  { value: "software", label: "Software" },
  { value: "hardware", label: "Hardware" },
  { value: "gadgets", label: "Gadgets" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "blockchain", label: "Blockchain" },
  { value: "programming", label: "Programming" },
  { value: "health", label: "Health" },
  { value: "wellness", label: "Wellness" },
  { value: "fitness", label: "Fitness" },
  { value: "nutrition", label: "Nutrition" },
  { value: "mental_health", label: "Mental Health" },
  { value: "medical_research", label: "Medical Research" },
  { value: "disease", label: "Disease" },
  { value: "healthcare", label: "Healthcare" },
  { value: "medicine", label: "Medicine" },
  { value: "science", label: "Science" },
  { value: "research", label: "Research" },
  { value: "astronomy", label: "Astronomy" },
  { value: "biology", label: "Biology" },
  { value: "physics", label: "Physics" },
  { value: "chemistry", label: "Chemistry" },
  { value: "space_exploration", label: "Space Exploration" },
  { value: "genetics", label: "Genetics" },
  { value: "climate_science", label: "Climate Science" },
  { value: "entertainment", label: "Entertainment" },
  { value: "movies", label: "Movies" },
  { value: "music", label: "Music" },
  { value: "celebrities", label: "Celebrities" },
  { value: "TV_shows", label: "TV Shows" },
  { value: "theater", label: "Theater" },
  { value: "fashion", label: "Fashion" },
  { value: "award_shows", label: "Award Shows" },
  { value: "books", label: "Books" },
  { value: "sports", label: "Sports" },
  { value: "football", label: "Football" },
  { value: "basketball", label: "Basketball" },
  { value: "baseball", label: "Baseball" },
  { value: "soccer", label: "Soccer" },
  { value: "tennis", label: "Tennis" },
  { value: "olympics", label: "Olympics" },
  { value: "athletes", label: "Athletes" },
  { value: "fitness", label: "Fitness" },
  { value: "lifestyle", label: "Lifestyle" },
  { value: "travel", label: "Travel" },
  { value: "food", label: "Food" },
  { value: "home", label: "Home" },
  { value: "fashion", label: "Fashion" },
  { value: "beauty", label: "Beauty" },
  { value: "hobbies", label: "Hobbies" },
  { value: "parenting", label: "Parenting" },
  { value: "relationships", label: "Relationships" },
  { value: "world_news", label: "World News" },
  { value: "international", label: "International" },
  { value: "global_events", label: "Global Events" },
  { value: "diplomacy", label: "Diplomacy" },
  { value: "war", label: "War" },
  { value: "conflict", label: "Conflict" },
  { value: "treaties", label: "Treaties" },
  { value: "foreign_policy", label: "Foreign Policy" },
  { value: "environment", label: "Environment" },
  { value: "climate_change", label: "Climate Change" },
  { value: "conservation", label: "Conservation" },
  { value: "sustainability", label: "Sustainability" },
  { value: "wildlife", label: "Wildlife" },
  { value: "renewable_energy", label: "Renewable Energy" },
  { value: "pollution", label: "Pollution" },
  { value: "natural_disasters", label: "Natural Disasters" },
  { value: "education", label: "Education" },
  { value: "schools", label: "Schools" },
  { value: "universities", label: "Universities" },
  { value: "learning", label: "Learning" },
  { value: "teaching", label: "Teaching" },
  { value: "scholarships", label: "Scholarships" },
  { value: "online_learning", label: "Online Learning" },
  { value: "curriculum", label: "Curriculum" },
  { value: "opinion", label: "Opinion" },
  { value: "editorials", label: "Editorials" },
  { value: "commentary", label: "Commentary" },
  { value: "analysis", label: "Analysis" },
  { value: "perspectives", label: "Perspectives" },
  { value: "columns", label: "Columns" },
  { value: "reviews", label: "Reviews" },
];
const ReactSelect = ({ field }) => {
  return (
    <Select
      options={options}
      closeMenuOnSelect={false}
      components={animatedComponents}
      isMulti
      {...field}
    />
  );
};

ReactSelect.propTypes = {
  field: PropTypes.object.isRequired,
};

export default ReactSelect;
